# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP app to Azure Web App - Thinksite

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup MSBuild path
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5

      - name: Restore NuGet packages
        run: nuget restore

      - name: Publish to folder
        run: msbuild /nologo /verbosity:m /t:Build /t:pipelinePreDeployCopyAllFilesToOneFolder /p:_PackageTempDir="\published\"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: ASP-app
          path: '/published/**'

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: $https://thinksite.azurewebsites.net

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: ASP-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'Thinksite'
          slot-name: 'Production'
          publish-profile: $<publishData><publishProfile profileName="Thinksite - Web Deploy" publishMethod="MSDeploy" publishUrl="thinksite.scm.azurewebsites.net:443" msdeploySite="Thinksite" userName="$Thinksite" userPWD="Rsf0fLM28aqXmDMfPg15hPnSk0Zi8hQZFXXmLkjxNMGBcPTR704XXLHaA5m1" destinationAppUrl="https://thinksite.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="http://windows.azure.com" webSystem="WebSites"><databases /></publishProfile><publishProfile profileName="Thinksite - FTP" publishMethod="FTP" publishUrl="ftps://waws-prod-dm1-187.ftp.azurewebsites.windows.net/site/wwwroot" ftpPassiveMode="True" userName="Thinksite\$Thinksite" userPWD="Rsf0fLM28aqXmDMfPg15hPnSk0Zi8hQZFXXmLkjxNMGBcPTR704XXLHaA5m1" destinationAppUrl="https://thinksite.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="http://windows.azure.com" webSystem="WebSites"><databases /></publishProfile><publishProfile profileName="Thinksite - Zip Deploy" publishMethod="ZipDeploy" publishUrl="thinksite.scm.azurewebsites.net:443" userName="$Thinksite" userPWD="Rsf0fLM28aqXmDMfPg15hPnSk0Zi8hQZFXXmLkjxNMGBcPTR704XXLHaA5m1" destinationAppUrl="https://thinksite.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="http://windows.azure.com" webSystem="WebSites"><databases /></publishProfile></publishData>}}
          package: .
